### ISSUE TITLE
Can not find a way to remove the fixed bar

### ISSUE THREAD

**Issue by cole-rogers** [naro143/hugo-coder-portfolio#1]
I do not have any fixed bar content, yet the fixed bar is still showing up. There is just a white bar floating on my web page. I do not want this. Using Hugo 37.1 on Fedora.

**Comment by naro143** [comment]
Hello @retiform.
Thank you for report.
I fixed it.
Please confirm it.

Thank you.

**Comment by cole-rogers** [comment]
It seems to be working now.
