### ISSUE TITLE
Uses Rawgit, which will be shutdown in October of this year.

### ISSUE THREAD

**Issue by cole-rogers** [naro143/hugo-coder-portfolio#10]
It is just pulling in: https://cdn.rawgit.com/necolas/normalize.css/master/normalize.css

From this file: https://github.com/naro143/hugo-coder-portfolio/blob/00ada23c6b1d295be244dc1e56fca8c63d1df9c8/layouts/_default/baseof.html

Could be severed with:
* https://unpkg.com/normalize.css@8.0.1/
* https://cdn.jsdelivr.net/npm/normalize.css@8.0.1/
* https://necolas.github.io/normalize.css/8.0.1/normalize.css

Or just hosted locally, as it really is a small file, and would prevent playing this game of cdn hopping again. Currently writing a patch to do this. (Will increase delievery size from server by about 3K, or 5%) Probably not important.

**Comment by naro143** [comment]
@retiform 
Thank you for report and pull request.
I did a merge.
Thank you very much！
