### ISSUE TITLE
Demo Page Cannot Find CSS Assets at themes.gohugo.io/theme/hugo-coder-portfolio

### ISSUE THREAD

**Issue by hdevilbiss** [naro143/hugo-coder-portfolio#28]
### Demo Page 404 on CSS Assets
The Demo page accessible from the [Hugo themes page](https://themes.gohugo.io/) cannot find its CSS files.

[https://themes.gohugo.io/theme/hugo-coder-portfolio/](https://themes.gohugo.io/theme/hugo-coder-portfolio/)

**These are the missing (404) files according to Network Monitor**
themes.gohugo.io/css/normalize.min.css
themes.gohugo.io/css/style.min.css
themes.gohugo.io/images/favicon-32x32.png

It works just fine as a fresh install on localhost! The theme loads the assets OK (200)
localhost:1313/css/normalize.min.css
localhost:1313/css/style.min.css

Is it possible that the theme at the host _themes.gohugo.io_ does not have PR #24 pulled in?

Anyway, thanks for the nice theme.

**Comment by naro143** [comment]
Hello @shed-00.
Thank you for report.
I fixed it.
Please confirm it.

Thank you.

**Comment by hdevilbiss** [comment]
Perfect!

If anyone else reading this needs to update their theme submodule:
[https://stackoverflow.com/a/5828396/12621376](https://stackoverflow.com/a/5828396/12621376)
