### ISSUE TITLE
Small dot appearing on the navbar when langseparator is not empty

### ISSUE THREAD

**Issue by dvcarrillo** [naro143/hugo-coder-portfolio#5]
Hi,

A small dot appears just above the language separator when this is not empty.
Looking with the inspector, it seems that it is the separator for the mobile menu.

<img width="777" alt="captura de pantalla 2018-10-04 a las 18 47 07" src="https://user-images.githubusercontent.com/12817239/46489736-7ac6ad80-c806-11e8-9f05-41d36bc13e72.png">

I'm using Safari 12 on macOS

**Comment by naro143** [comment]
Hello @dvcarrillo 
Thank you for report.
Please tell me more about this issue because I am not good at English.
Sorry.

**Comment by dvcarrillo** [comment]
No problem!

This small dot:
<img width="777" alt="46489736-7ac6ad80-c806-11e8-9f05-41d36bc13e72" src="https://user-images.githubusercontent.com/12817239/46864067-7eb38a80-ce19-11e8-9c9d-8c87807a50e1.png">
Appears when ```langseparator``` is not empty. 

Using the web inspector I have noticed the following:
<img width="1183" alt="captura de pantalla 2018-10-12 a las 12 21 15" src="https://user-images.githubusercontent.com/12817239/46864164-c508e980-ce19-11e8-85b8-e28438b63d91.png">

I assume it should not appear for desktop resolutions.

I hope this can help :)

**Comment by naro143** [comment]
Hello @dvcarrillo.
I fixedI fixed it.
Please confirm it.

Thank you.

**Comment by dvcarrillo** [comment]
It's fixed.

Thank you! 😊
