### ISSUE TITLE
Change Social Sharing

### ISSUE THREAD

**Issue by 19neo79** [naro143/hugo-coder-portfolio#9]
Hello! Thank you for the great work you are doing. A question .. where do I find the possibility to remove the bar in the footer? And how can I delete some social media that are not famous here in Italy? (like Hatena and Line.me) Thank you very much

**Comment by naro143** [comment]
@19neo79 
Thank you for message.
If you want to invalidate sns share, set snsShare in config.toml to "false".
If you want to set one by one, change "/hugo-coder-portfolio/layouts/partials/footer.html".

**Comment by cole-rogers** [comment]
@19neo79 I believe one of the settings in the config.toml turns on/off the footer bar. Might be 
`hideCredits = true`

**Comment by naro143** [comment]
@19neo79 
Sorry for replying so late.

Done.
Add params to config. it and sns are one-to-one.
```
enableTwitterShare = true
enableFacebookShare = true
enableHatenaShare = true
enableLineShare = true
```
Because embedding a DOM from config is difficult with Hugo.
